# Generated by Django 4.1.7 on 2023-04-13 07:01

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_poster', models.FilePathField(path=movies.models.poster_path)),
                ('movie_about', models.TextField()),
            ],
        ),
    ]
