# Generated by Django 4.1.7 on 2023-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название фильма')),
                ('poster', models.ImageField(upload_to='poster', verbose_name='Постер')),
                ('about', models.TextField(blank=True, verbose_name='О фильме')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Дата добавления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Фильмы',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['date_create', 'id', 'title'],
            },
        ),
    ]
