# Generated by Django 4.1.7 on 2023-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('poster', models.ImageField(upload_to='poster')),
                ('about', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
    ]
