# Generated by Django 4.1.7 on 2023-04-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='release_dates',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
