# Generated by Django 4.1.7 on 2023-04-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
