# Generated by Django 4.1.7 on 2023-04-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_release_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_dates',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
