# Generated by Django 4.1.7 on 2023-04-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_poster',
        ),
    ]
