# Generated by Django 4.1.7 on 2023-04-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_name_movies_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='title',
            new_name='name',
        ),
    ]
