# Generated by Django 4.1.7 on 2023-04-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_title_movies_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='title',
        ),
    ]
