# Generated by Django 4.1.7 on 2023-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_name_movies_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date_create',
            field=models.DateTimeField(blank=True),
        ),
    ]
