# Generated by Django 4.1.7 on 2023-04-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movies_options_remove_movies_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
