# Generated by Django 4.1.7 on 2023-04-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movies_date_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['date_create', 'id', 'title'], 'verbose_name': 'Фильмы', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
