# Generated by Django 4.1.7 on 2023-04-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='about',
            field=models.TextField(blank=True, verbose_name='О фильме'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(upload_to='poster', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название фильма'),
        ),
    ]
